version: '3.8'

services:
  terminology:
    image: open-ortho/terminology:latest
    ports:
      - "8000:8000"
    environment:
      OT_VERBOSITY: 2
      OT_FHIR_API: "True"
      OT_DATABASE_FILE: "/var/lib/oo-terminology/sqlite3.db"
      OT_CONFIGURATOR_UI: "False"
      OT_FLASK_SECRET_KEY: "your_flask_secret_key"
      OT_WEB_LISTEN: "0.0.0.0"
      OT_WEB_PORT: "5000"
      OT_FHIR_LISTEN: "0.0.0.0"
      OT_FHIR_PORT: "8000"