import json
import unittest
from pathlib import Path
import tempfile

from terminology.main import (
    build_index_entry,
    collect_index_entries,
    generate_index,
    get_all_code_systems,
    save_fhir_resource,
    expand_valueset,
    FHIR_BASE_URL,
)
from terminology.fhir_types import CodeSystem, ValueSet, ConceptMap
from terminology.resources.code_systems import ada_1100_extraoral_2d_photographic_scheduled_protocol
from terminology.resources.code_systems import (
    dentaleyepad_image_types,
    cwru_ortho_image_types,
    ada_1100_extraoral_3d_visible_light_scheduled_protocol,
    ada_1100_intraoral_3d_visible_light_scheduled_protocol,
    ada_1100_intraoral_2d_photographic_scheduled_protocol,
    ada_1100_enumerated_terms,
)
from terminology.resources.value_sets import scheduled_protocol, cwru_ortho_image_types as cwru_ortho_record_types_value_sets
from terminology.resources.value_sets import cwru_ortho_record_type_extra
from terminology.resources.value_sets import open_ortho_value_sets
from terminology.resources.concept_maps import orthodontic_photograph_views
from terminology.resources.value_sets.cwru_ortho_record_type_extra import (
    CWRUOrthoRecordTypesAcetateFilm,
    CWRUOrthoRecordTypesPaper,
    CWRUOrthoRecordTypesGypsum,
)
from terminology.resources.concept_maps.orthodontic_photograph_views import (
    OrthodonticPhotographViewsConceptMap,
    OrthodonticPhotographViewsReverseConceptMap,
)
from terminology.resources.naming_systems import ADA1100NamingSystem


def _make_resources():
    return {
        CodeSystem: [
            ada_1100_extraoral_2d_photographic_scheduled_protocol,
            ada_1100_extraoral_3d_visible_light_scheduled_protocol,
            ada_1100_intraoral_3d_visible_light_scheduled_protocol,
            ada_1100_intraoral_2d_photographic_scheduled_protocol,
            dentaleyepad_image_types,
            cwru_ortho_image_types,
            ada_1100_enumerated_terms,
        ],
        ValueSet: [
            scheduled_protocol,
            cwru_ortho_record_types_value_sets,
            cwru_ortho_record_type_extra,
            open_ortho_value_sets,
        ],
        ConceptMap: [
            orthodontic_photograph_views,
        ],
    }


class TestMain(unittest.TestCase):

    def test_get_all_code_systems(self):
        all_code_systems = get_all_code_systems()
        self.assertIsInstance(all_code_systems, dict)
        self.assertTrue(all_code_systems)
        self.assertTrue(all_code_systems.get(
            ada_1100_extraoral_2d_photographic_scheduled_protocol
            .Extraoral2DPhotographicScheduledProtocolCodeSystem().url
        ))

    def test_generate_index(self):
        resources = _make_resources()
        index_entries = collect_index_entries(resources)

        with tempfile.TemporaryDirectory() as temp_dir:
            output_path = Path(temp_dir) / "index.html"
            generate_index(index_entries, output_path)
            self.assertTrue(output_path.exists())
            content = output_path.read_text(encoding="ascii")
            self.assertIn("AUTOGENERATED FILE - DO NOT EDIT.", content)
            self.assertIn("<h2>CodeSystems</h2>", content)
            self.assertIn("<h2>ValueSets</h2>", content)
            self.assertIn("<h2>ConceptMaps</h2>", content)
            # New sid/ URL structure
            self.assertIn("sid/ada1100/CodeSystem/extraoral-2d-photographic-scheduled-protocol", content)

    def test_generate_index_with_naming_systems_uses_utf8(self):
        resources = _make_resources()
        naming_system = ADA1100NamingSystem()
        naming_system_entries = [build_index_entry(naming_system)]
        index_entries = collect_index_entries(resources, naming_system_entries)

        with tempfile.TemporaryDirectory() as temp_dir:
            output_path = Path(temp_dir) / "index.html"
            generate_index(index_entries, output_path, naming_system_entries)
            self.assertTrue(output_path.exists())
            content = output_path.read_text(encoding="utf-8")
            self.assertIn("<h2>NamingSystems</h2>", content)
            self.assertIn(str(naming_system.url), content)
            self.assertIn("ANSI/ADA Standard No. 1100 — Dental Informatics", content)

    def test_valueset_output_uses_directory_structure(self):
        """ValueSets are written as <slug>/index.html and <slug>/$expand, not flat files."""
        all_code_systems = get_all_code_systems()
        with tempfile.TemporaryDirectory() as temp_dir:
            fhir_dir = Path(temp_dir) / "fhir"
            fhir_dir.mkdir()
            save_fhir_resource(scheduled_protocol, ValueSet, fhir_dir, all_code_systems)

            # Derive expected path from canonical URL (same logic as save_fhir_resource)
            from terminology.resources.value_sets.scheduled_protocol import ScheduledProtocolValueSet
            vs_url = str(ScheduledProtocolValueSet().url)
            relative = vs_url.removeprefix(FHIR_BASE_URL).lstrip("/")
            slug_dir = fhir_dir / relative

            self.assertTrue(slug_dir.is_dir(), f"Expected a directory at fhir/{relative}/")
            self.assertTrue((slug_dir / "index.html").exists(), "Expected index.html inside the ValueSet directory")
            self.assertTrue((slug_dir / "$expand").exists(), "Expected $expand file inside the ValueSet directory")

    def test_expand_valueset_respects_concept_filter(self):
        """Concept-filtered ValueSets expand to only their pinned codes, not all CS codes."""
        all_code_systems = get_all_code_systems()

        # AcetateFilm pins: L, F, OB, OC, P, FA, H, CS, E, K  (10 codes)
        acetate = CWRUOrthoRecordTypesAcetateFilm()
        expanded_acetate = expand_valueset(acetate, all_code_systems)
        acetate_codes = {c.code for c in (expanded_acetate.expansion.contains or [])}
        self.assertEqual(acetate_codes, {"L", "F", "OB", "OC", "P", "FA", "H", "CS", "E", "K"},
                         "AcetateFilm expansion must contain exactly its 10 pinned codes")

        # Paper pins: RE, RF  (2 codes)
        paper = CWRUOrthoRecordTypesPaper()
        expanded_paper = expand_valueset(paper, all_code_systems)
        paper_codes = {c.code for c in (expanded_paper.expansion.contains or [])}
        self.assertEqual(paper_codes, {"RE", "RF"},
                         "Paper expansion must contain exactly its 2 pinned codes")

        # Gypsum pins: SM, SU, SL, FM  (4 codes)
        gypsum = CWRUOrthoRecordTypesGypsum()
        expanded_gypsum = expand_valueset(gypsum, all_code_systems)
        gypsum_codes = {c.code for c in (expanded_gypsum.expansion.contains or [])}
        self.assertEqual(gypsum_codes, {"SM", "SU", "SL", "FM"},
                         "Gypsum expansion must contain exactly its 4 pinned codes")

    def test_expand_file_content_is_valid_json(self):
        "$expand file must contain valid JSON with expansion.contains populated."
        all_code_systems = get_all_code_systems()
        with tempfile.TemporaryDirectory() as temp_dir:
            fhir_dir = Path(temp_dir) / "fhir"
            fhir_dir.mkdir()
            save_fhir_resource(scheduled_protocol, ValueSet, fhir_dir, all_code_systems)

            from terminology.resources.value_sets.scheduled_protocol import ScheduledProtocolValueSet
            vs_url = str(ScheduledProtocolValueSet().url)
            relative = vs_url.removeprefix(FHIR_BASE_URL).lstrip("/")
            expand_file = fhir_dir / relative / "$expand"

            self.assertTrue(expand_file.exists())
            data = json.loads(expand_file.read_text(encoding="utf-8"))
            self.assertIn("expansion", data)
            self.assertIn("contains", data["expansion"])
            self.assertGreater(len(data["expansion"]["contains"]), 0,
                               "$expand must have at least one code in expansion.contains")

    def test_ortho_photograph_views_valueset_generates_files(self):
        """OrthodonticPhotographViewsValueSet generates index.html and $expand."""
        all_code_systems = get_all_code_systems()
        with tempfile.TemporaryDirectory() as temp_dir:
            fhir_dir = Path(temp_dir) / "fhir"
            fhir_dir.mkdir()
            save_fhir_resource(open_ortho_value_sets, ValueSet, fhir_dir, all_code_systems)

            from terminology.resources.value_sets.open_ortho_value_sets import OrthodonticPhotographViewsValueSet
            vs_url = str(OrthodonticPhotographViewsValueSet().url)
            relative = vs_url.removeprefix(FHIR_BASE_URL).lstrip("/")
            slug_dir = fhir_dir / relative

            self.assertTrue(slug_dir.is_dir(), f"Expected directory at fhir/{relative}")
            self.assertTrue((slug_dir / "index.html").exists())
            self.assertTrue((slug_dir / "$expand").exists())


class TestConceptMapGeneratorRoundTrip(unittest.TestCase):
    """Verify that generated ConceptMap JSON has the structure the generator tool expects.

    The JS tool (tools/conceptmap-generator.html) loads ConceptMaps via parseConceptMap(),
    which reads: json.group[].target (string URL), json.group[].element[].code (string),
    json.group[].element[].target[].code (string), json.group[].element[].target[].relationship.
    These tests ensure that structure is present so round-trip load works.
    """

    def _dump(self, instance):
        return instance.model_dump(mode="json")

    def test_conceptmap_has_required_resourcetype(self):
        cm = self._dump(OrthodonticPhotographViewsConceptMap())
        self.assertEqual(cm["resourceType"], "ConceptMap")

    def test_conceptmap_has_groups(self):
        cm = self._dump(OrthodonticPhotographViewsConceptMap())
        self.assertIn("group", cm)
        self.assertIsInstance(cm["group"], list)
        self.assertGreater(len(cm["group"]), 0, "ConceptMap must have at least one group")

    def test_conceptmap_groups_have_target_url(self):
        """Each group must have a 'target' string — the target CodeSystem URL."""
        cm = self._dump(OrthodonticPhotographViewsConceptMap())
        for i, group in enumerate(cm["group"]):
            self.assertIn("target", group, f"group[{i}] missing 'target'")
            self.assertIsInstance(group["target"], str, f"group[{i}].target must be a string")
            self.assertTrue(group["target"].startswith("http"), f"group[{i}].target must be a URL")

    def test_conceptmap_groups_have_source_url(self):
        """Each group must have a 'source' string — used to auto-detect source CS on reload."""
        cm = self._dump(OrthodonticPhotographViewsConceptMap())
        for i, group in enumerate(cm["group"]):
            self.assertIn("source", group, f"group[{i}] missing 'source'")
            self.assertIsInstance(group["source"], str, f"group[{i}].source must be a string")

    def test_conceptmap_elements_have_mapped_codes(self):
        """Each element must have a 'code' and at least one target with a 'code'."""
        cm = self._dump(OrthodonticPhotographViewsConceptMap())
        for g_idx, group in enumerate(cm["group"]):
            for e_idx, elem in enumerate(group.get("element", [])):
                self.assertIn("code", elem, f"group[{g_idx}].element[{e_idx}] missing 'code'")
                targets = elem.get("target", [])
                self.assertGreater(len(targets), 0,
                    f"group[{g_idx}].element[{e_idx}] has no target mappings")
                for t_idx, tgt in enumerate(targets):
                    self.assertIn("code", tgt,
                        f"group[{g_idx}].element[{e_idx}].target[{t_idx}] missing 'code'")
                    self.assertIn("relationship", tgt,
                        f"group[{g_idx}].element[{e_idx}].target[{t_idx}] missing 'relationship'")

    def test_reverse_conceptmap_has_correct_structure(self):
        """The reverse ConceptMap must also have valid group/element/target structure."""
        cm = self._dump(OrthodonticPhotographViewsReverseConceptMap())
        self.assertEqual(cm["resourceType"], "ConceptMap")
        self.assertGreater(len(cm.get("group", [])), 0)
        for group in cm["group"]:
            self.assertIn("target", group)
            for elem in group.get("element", []):
                self.assertIn("code", elem)

    def test_conceptmap_url_is_canonical(self):
        """ConceptMap canonical URL must be on terminology.open-ortho.org."""
        cm = self._dump(OrthodonticPhotographViewsConceptMap())
        self.assertIn("terminology.open-ortho.org", cm["url"])

    def test_conceptmap_file_is_loadable_from_docs(self):
        """The built ConceptMap JSON file in docs/ is valid and matches the Python source."""
        built = Path("docs/fhir/ConceptMap/orthodontic-photograph-views")
        if not built.exists():
            self.skipTest("docs/fhir/ not built — run 'make build' first")
        data = json.loads(built.read_text())
        self.assertEqual(data["resourceType"], "ConceptMap")
        expected_url = OrthodonticPhotographViewsConceptMap().url
        self.assertEqual(data["url"], str(expected_url))
        self.assertEqual(data["version"], OrthodonticPhotographViewsConceptMap().version)
        self.assertGreater(len(data.get("group", [])), 0)


if __name__ == '__main__':
    unittest.main()
