import unittest
from pathlib import Path
import tempfile

from terminology.main import get_all_code_systems, generate_index
from terminology.fhir_types import CodeSystem, ValueSet, ConceptMap
from terminology.resources.code_systems import extraoral_2d_photographic_scheduled_protocol
from terminology.resources.code_systems import (
    dentaleyepad_image_types,
    cwru_ortho_image_types,
    extraoral_3d_visible_light_scheduled_protocol,
    intraoral_3d_visible_light_scheduled_protocol,
    intraoral_2d_photographic_scheduled_protocol,
    ada_1100_enumerated_terms,
)
from terminology.resources.value_sets import scheduled_protocol, cwru_ortho_image_types
from terminology.resources.value_sets import cwru_ortho_record_type_extra
from terminology.resources.concept_maps import orthodontic_photograph_views

class TestMain(unittest.TestCase):

    def test_get_all_code_systems(self):
        all_code_systems = get_all_code_systems()
        self.assertIsInstance(all_code_systems, dict)
        self.assertTrue(all_code_systems)
        self.assertTrue(all_code_systems.get(extraoral_2d_photographic_scheduled_protocol.Extraoral2DPhotographicScheduledProtocolCodeSystem().url))

    def test_generate_index(self):
        resources = {
            CodeSystem: [
                extraoral_2d_photographic_scheduled_protocol,
                extraoral_3d_visible_light_scheduled_protocol,
                intraoral_3d_visible_light_scheduled_protocol,
                intraoral_2d_photographic_scheduled_protocol,
                dentaleyepad_image_types,
                cwru_ortho_image_types,
                ada_1100_enumerated_terms,
            ],
            ValueSet: [
                scheduled_protocol,
                cwru_ortho_image_types,
                cwru_ortho_record_type_extra,
            ],
            ConceptMap: [
                orthodontic_photograph_views,
            ],
        }

        with tempfile.TemporaryDirectory() as temp_dir:
            output_path = Path(temp_dir) / "index.html"
            generate_index(resources, output_path)
            self.assertTrue(output_path.exists())
            content = output_path.read_text(encoding="ascii")
            self.assertIn("AUTOGENERATED FILE - DO NOT EDIT.", content)
            self.assertIn("<h2>CodeSystems</h2>", content)
            self.assertIn("<h2>ValueSets</h2>", content)
            self.assertIn("<h2>ConceptMaps</h2>", content)
            self.assertIn(
                "<a href=\"http://terminology.open-ortho.org/fhir/extraoral-2d-photographic-scheduled-protocol\">http://terminology.open-ortho.org/fhir/extraoral-2d-photographic-scheduled-protocol</a>",
                content,
            )

if __name__ == '__main__':
    unittest.main()
