#!/usr/bin/env python3
""" Convert Python code modules to JSON and CSV for publication.

When adding new modules:

- Import module
- Add new module to for loop in __main__
"""
import json
import logging
import sys
import types
from pathlib import Path
from datetime import datetime
from typing import Any, Type

from fhir.resources.resource import Resource
from pydantic import ValidationError

from terminology.fhir_types import (
    CodeSystem,
    ConceptMap,
    ValueSet,
    ValueSetExpansion,
    ValueSetExpansionContains,
)

from terminology.resources.code_systems import (
    dentaleyepad_image_types,
    cwru_ortho_image_types,
    ada_1100_extraoral_2d_photographic_scheduled_protocol,
    ada_1100_extraoral_3d_visible_light_scheduled_protocol,
    ada_1100_intraoral_3d_visible_light_scheduled_protocol,
    ada_1100_intraoral_2d_photographic_scheduled_protocol,
    ada_1100_enumerated_terms,
    topsortho_ccd8ebb7_image_label_types,
)

from terminology.resources.concept_maps import orthodontic_photograph_views
from terminology.resources.value_sets import scheduled_protocol, cwru_ortho_image_types as cwru_ortho_record_types_value_sets
from terminology.resources.value_sets import cwru_ortho_record_type_extra
from terminology.resources.value_sets import open_ortho_value_sets

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Create console handler and set level to debug
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)

# Create formatter and add it to the handler
log_formatter = logging.Formatter(
    "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
console_handler.setFormatter(log_formatter)

# Add the handler to the logger
logger.addHandler(console_handler)


build_path = Path(".", "docs")
FHIR_BASE_URL = "https://terminology.open-ortho.org/fhir"

def build_index_entry(resource: Resource) -> dict[str, str]:
    title = getattr(resource, "title", None) or getattr(resource, "name", None) or ""
    description = getattr(resource, "description", None) or ""
    url = str(getattr(resource, "url", ""))
    resource_type = getattr(resource, "resource_type", None) or getattr(
        resource, "__resource_type__", ""
    )
    expand_url = f"{url}/$expand" if resource_type == "ValueSet" and url else ""
    return {
        "resource_type": resource_type,
        "title": title,
        "description": description,
        "url": url,
        "expand_url": expand_url,
    }

def generate_index(resources: dict[Type[Resource], list[Any]], output_path: Path) -> None:
    index_entries: dict[str, list[dict[str, str]]] = {
        "CodeSystem": [],
        "ValueSet": [],
        "ConceptMap": [],
    }

    def escape_html(text: str) -> str:
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )

    for resource_type, modules in resources.items():
        for module in modules:
            for name in dir(module):
                obj = getattr(module, name)
                if isinstance(obj, type) and issubclass(obj, resource_type):
                    if obj == resource_type:
                        continue
                    instance = obj()
                    if not instance.url:
                        continue
                    entry = build_index_entry(instance)
                    index_entries[entry["resource_type"]].append(entry)

    # HTML file content
    lines = [
        "<!DOCTYPE html>",
        "<html lang=\"en\">",
        "<head>",
        "    <meta charset=\"UTF-8\">",
        "    <title>Open Ortho Terminology Index</title>",
        "    <style>",
        "      body { font-family: Arial, sans-serif; max-width: 900px; margin: auto; padding: 2em; background: #fff; color: #222; }",
        "      table { border-collapse: collapse; width: 100%; margin-bottom: 2em; }",
        "      th, td { border: 1px solid #bbb; padding: 0.5em 1em; text-align: left; }",
        "      th { background: #e8e8e8; }",
        "      caption { caption-side: top; font-weight: bold; margin: 0.5em 0; }",
        "      .warning { color: #b00; font-size: 1.1em; margin-bottom: 1em; }",
        "    </style>",
        "</head>",
        "<body>",
        "<!-- AUTOGENERATED FILE - DO NOT EDIT.",
        "     This file is generated by the build script. Update sources, then rebuild. -->",
        "<h1>Open Ortho Terminology Index</h1>",
        "<p>This site publishes code systems, value sets, and concept maps in FHIR format, generated by the <code>open-ortho/terminology</code> project. ",
        "A <a href=\"../conceptmap-generator.html\">ConceptMap editor</a> tool is also available.<br><br>",
        "All URLs reference the canonical published format at <a href=\"https://terminology.open-ortho.org/\">https://terminology.open-ortho.org/</a>.</p>",
    ]

    for section in ("CodeSystem", "ValueSet", "ConceptMap"):
        entries = sorted(
            index_entries[section],
            key=lambda item: (item["title"].lower(), item["url"]),
        )
        lines.append(f"<h2>{section}s</h2>")
        if not entries:
            lines.append("<p>(None)</p>")
            continue
        lines.append("<table>")
        if section == "ValueSet":
            lines.append("<tr><th>Title</th><th>URL</th><th>$expand</th><th>Description</th></tr>")
        else:
            lines.append("<tr><th>Title</th><th>URL</th><th>Description</th></tr>")
        for entry in entries:
            title = escape_html(entry["title"]) or entry["url"]
            desc = escape_html(entry["description"]) if entry["description"] else ""
            url = entry["url"]
            link = f'<a href="{url}">{url}</a>' if url else ""
            if section == "ValueSet":
                expand_url = entry.get("expand_url", "")
                expand_link = f'<a href="{expand_url}">{expand_url}</a>' if expand_url else ""
                lines.append(f"<tr><td>{title}</td><td>{link}</td><td>{expand_link}</td><td>{desc}</td></tr>")
            else:
                lines.append(f"<tr><td>{title}</td><td>{link}</td><td>{desc}</td></tr>")
        lines.append("</table>")

    lines.append("</body>")
    lines.append("</html>")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="ascii")

def expand_valueset(valueset: ValueSet, all_code_systems: dict[str, CodeSystem]) -> ValueSet:
    """Expand a ValueSet by including all codes from referenced CodeSystems.

    Args:
        valueset: ValueSet instance to expand
        all_code_systems: Dictionary of all available CodeSystem resources

    Returns:
        ValueSet containing the expanded ValueSet with all codes included
    """
    # Create a new ValueSet for expansion
    expanded = ValueSet(**valueset.model_dump())

    # Create expansion
    contains: list[ValueSetExpansionContains] = []

    if not valueset.compose or not valueset.compose.include:
        return expanded

    includes = valueset.compose.include or []

    # Process each included system
    for include in includes:
        system_url = include.system
        if not system_url:
            continue

        # Find the referenced CodeSystem instance
        cs_instance = all_code_systems.get(system_url)

        if cs_instance:
            # If include.concept is non-empty, only include those specific codes
            pinned_codes = {c.code for c in (include.concept or [])} if include.concept else set()
            concepts = cs_instance.concept or []
            for concept in concepts:
                if not pinned_codes or concept.code in pinned_codes:
                    contains.append(
                        ValueSetExpansionContains(
                            system=system_url,
                            code=concept.code,
                            display=concept.display,
                        )
                    )
        else:
            logger.warning(f"CodeSystem with URL {system_url} not found.")

    # Create and set the expansion
    expanded.expansion = ValueSetExpansion(
        timestamp=datetime.now().date().isoformat(),
        total=len(contains),
        contains=contains,
    )

    return expanded

def save_fhir_resource(
    module: Any,
    resource_type: Type[Resource],
    filename: Path,
    all_code_systems: dict[str, CodeSystem],
) -> None:
    """Save any FHIR resource to JSON file.

    Args:
        module: Python module containing FHIR resource classes
        resource_type: Type of FHIR resource to look for (CodeSystem, ValueSet, etc)
        filename: Base path where to save the JSON files
    """
    logger.info(f"Processing {module.__name__} for {resource_type.__name__}")

    resources = {
        name: getattr(module, name) for name in dir(module)
        if isinstance(getattr(module, name), type)
        and issubclass(getattr(module, name), resource_type)
    }

    if not resources:
        logger.warning(
            f"No {resource_type.__name__} instances found in module {module.__name__}")
        return

    for _, resource_class in resources.items():
        if resource_class == resource_type:
            # Skip the base classes
            continue
        try:
            resource_instance = resource_class()

            if not resource_instance.url:
                logger.warning(
                    f"Skipping {resource_class.__name__}; missing canonical URL"
                )
                continue

            # Derive output path from canonical URL relative to FHIR base
            relative_path = str(resource_instance.url).removeprefix(FHIR_BASE_URL).lstrip("/")

            if isinstance(resource_instance, ValueSet):
                # ValueSets: write into a subdirectory so that $expand can live alongside
                # docs/fhir/sid/<ns>/ValueSet/<slug>/index.html  <- base resource
                # docs/fhir/sid/<ns>/ValueSet/<slug>/$expand     <- FHIR $expand response
                vs_dir = filename / relative_path
                vs_dir.mkdir(parents=True, exist_ok=True)

                base_filename = vs_dir / "index.html"
                logger.info(f"Saving {resource_class.__name__} to {base_filename}")
                with open(base_filename, "w", encoding="utf-8") as f:
                    json.dump(resource_instance.model_dump(mode="json"), f, indent=4)

                expand_filename = vs_dir / "$expand"
                logger.info(f"Saving expanded {resource_class.__name__} to {expand_filename}")
                expanded = expand_valueset(resource_instance, all_code_systems)
                with open(expand_filename, "w", encoding="utf-8") as f:
                    json.dump(expanded.model_dump(mode="json"), f, indent=4)
            else:
                base_filename = filename / relative_path
                base_filename.parent.mkdir(parents=True, exist_ok=True)

                # Save the basic resource
                logger.info(f"Saving {resource_class.__name__} to {base_filename}")
                with open(base_filename, "w", encoding="utf-8") as f:
                    json.dump(resource_instance.model_dump(mode="json"), f, indent=4)

        except ValidationError as exc:
            # logger.exception(e)
            logger.error(
                "%s %s is not valid: %s",
                resource_type.__name__,
                resource_class.__name__,
                exc,
            )
            continue

def get_all_code_systems() -> dict[str, CodeSystem]:
    """Collect all CodeSystem instances from the available modules.

    Returns:
        Dictionary of all available CodeSystem instances
    """
    from terminology.resources import code_systems

    all_code_systems: dict[str, CodeSystem] = {}
    for name in dir(code_systems):
        obj = getattr(code_systems, name)
        if isinstance(obj, types.ModuleType):
            for subname in dir(obj):
                subobj = getattr(obj, subname)
                if (
                    isinstance(subobj, type)
                    and issubclass(subobj, CodeSystem)
                    and subobj != CodeSystem
                ):
                    try:
                        instance = subobj()
                        if instance.url is not None:
                            all_code_systems[str(instance.url)] = instance
                    except (ValidationError, TypeError, ValueError) as exc:
                        logger.warning(
                            "Could not instantiate %s: %s",
                            subobj.__name__,
                            exc,
                        )
    return all_code_systems

def main() -> int:
    all_code_systems = get_all_code_systems()
    # Dictionary mapping resource types to modules containing them
    resources = {
        CodeSystem: [
            ada_1100_extraoral_2d_photographic_scheduled_protocol,
            ada_1100_extraoral_3d_visible_light_scheduled_protocol,
            ada_1100_intraoral_3d_visible_light_scheduled_protocol,
            ada_1100_intraoral_2d_photographic_scheduled_protocol,
            dentaleyepad_image_types,
            cwru_ortho_image_types,
            ada_1100_enumerated_terms,
            topsortho_ccd8ebb7_image_label_types,
        ],
        ValueSet: [
            scheduled_protocol,
            cwru_ortho_record_types_value_sets,
            cwru_ortho_record_type_extra,
            open_ortho_value_sets,
        ],
        ConceptMap: [
            orthodontic_photograph_views
        ]
    }

    # Process each resource type and its modules
    for resource_type, modules in resources.items():
        for module in modules:
            save_fhir_resource(module, resource_type, build_path / "fhir", all_code_systems)

    generate_index(resources, build_path / "index.html")

    return 0

if __name__ == "__main__":
    sys.exit(main())
