from datetime import datetime

from terminology.fhir_types import CodeSystem, CodeSystemConcept
from terminology.resources.naming_systems import MedocoHealthNamingSystem
from terminology.resources.code_systems import leave_code_as_is as make_code


id = "image-label-types"


class MRosaImageLabelTypesCodeSystem(CodeSystem):

    @classmethod
    def static_url(cls) -> str:
        return "http://topsortho.com/fhir/practice/CCD8EBB7-5A23-40B9-A8A7-AD3D6D14C4FE/CodeSystem/image-label-types"

    def __init__(self):
        ns = MedocoHealthNamingSystem()
        super().__init__(
            id=id,
            identifier=[
                {
                    "system": "urn:ietf:rfc:3986",
                    "value": "urn:oid:2.16.840.1.113883.3.12345.9.8"
                }
            ],
            url=self.static_url(),
            version="1.0.0",
            name="ImageLabelTypes",
            title="topsOrtho Image Label Types",
            status="active",
            experimental=False,
            date=datetime.now().date().isoformat(),
            publisher=ns.publisher,
            description="Image label types of topsOrtho. These define the types of images, such as panoramic x-ray or frontal smiling. The user can modify these.",
            caseSensitive=True,
            content="complete",
            concept=[
                CodeSystemConcept(code="1", display="TELE P-A", definition="Frontal Ceph X-Ray"),
                CodeSystemConcept(code="2", display="Tracciato TELE P-A", definition="Frontal Ceph X-Ray w/ Tracing"),
                CodeSystemConcept(code="4", display="6 MIP", definition="Left Intraoral Photo"),
                CodeSystemConcept(code="5", display="STL 6", definition="Left Models"),
                CodeSystemConcept(code="6", display="1 MIP labbra rilassate", definition="Portrait Profile"),
                CodeSystemConcept(code="9", display="TELE", definition="Lateral Ceph X-Ray"),
                CodeSystemConcept(code="10", display="Tracciato TELE", definition="Lateral Ceph X-Ray w/ Tracing"),
                CodeSystemConcept(code="11", display="8", definition="Occlusal Photo of Mandibular Dentition"),
                CodeSystemConcept(code="12", display="Modello Occlusale Mandibola", definition="Occlusal Photo of Mandibular Model"),
                CodeSystemConcept(code="13", display="Tracciato Occlusale Mandibola (Modello)", definition="Occlusal Tracing of Mandibular Model"),
                CodeSystemConcept(code="14", display="7", definition="Occlusal Photo of Maxillary Dentition"),
                CodeSystemConcept(code="15", display="Modello Occlusale Mascella", definition="Occlusal Photo of Maxillary Model"),
                CodeSystemConcept(code="18", display="OPT", definition="Panoramic X-Ray"),
                CodeSystemConcept(code="19", display="4 MIP", definition="Right Intraoral Photo"),
                CodeSystemConcept(code="20", display="STL 4", definition="Right Models"),
                CodeSystemConcept(code="25", display="1 sovrapp tracciato/testa 1", definition="Regional Lateral Ceph Tracing Superimposition A"),
                CodeSystemConcept(code="26", display="1 sovrapp tracciato/testa 2", definition="Regional Lateral Ceph Tracing Superimposition B"),
                CodeSystemConcept(code="27", display="Tracciato Laterale di Prev. Crescita", definition="Lateral Ceph VTO Tracing"),
                CodeSystemConcept(code="28", display="postura", definition="Full Body Photo"),
                CodeSystemConcept(code="29", display="3", definition="Portrait Smiling"),
                CodeSystemConcept(code="30", display="2 MIP labbra rilassate", definition="Portrait Relaxed Lips"),
                CodeSystemConcept(code="31", display="5 MIP", definition="Frontal Intraoral Photo"),
                CodeSystemConcept(code="32", display="STL 5", definition="Frontal Models"),
                CodeSystemConcept(code="33", display="2 tracciato 1", definition="Frontal Ceph Tracing"),
                CodeSystemConcept(code="34", display="2 foto/tracciato", definition="Portrait Relaxed Lips w/ Tracing"),
                CodeSystemConcept(code="35", display="5 video", definition="Frontal Intraoral Movie"),
                CodeSystemConcept(code="38", display="2 tracciato 2", definition="Frontal Ceph Tracing"),
                CodeSystemConcept(code="5001", display="Foto Simpatica 1"),
                CodeSystemConcept(code="5002", display="Legnetto PO"),
                CodeSystemConcept(code="5003", display="1 RO"),
                CodeSystemConcept(code="5004", display="2 SUB7"),
                CodeSystemConcept(code="5005", display="2 RO"),
                CodeSystemConcept(code="5006", display="1 S"),
                CodeSystemConcept(code="5007", display="RX1"),
                CodeSystemConcept(code="5008", display="RX2"),
                CodeSystemConcept(code="5009", display="RX3"),
                CodeSystemConcept(code="5010", display="RX4"),
                CodeSystemConcept(code="5011", display="RX5"),
                CodeSystemConcept(code="5012", display="GEN 1"),
                CodeSystemConcept(code="5013", display="6 P da sotto"),
                CodeSystemConcept(code="5014", display="5 BA"),
                CodeSystemConcept(code="5015", display="4 P da sotto"),
                CodeSystemConcept(code="5016", display="5 P sup / sfondo nero"),
                CodeSystemConcept(code="5017", display="2 SV"),
                CodeSystemConcept(code="5018", display="2 P"),
                CodeSystemConcept(code="5019", display="3 P"),
                CodeSystemConcept(code="5020", display="2 P RO"),
                CodeSystemConcept(code="5021", display="PL DIGA 1"),
                CodeSystemConcept(code="5022", display="SMORFIA"),
                CodeSystemConcept(code="5023", display="SMORFIA1"),
                CodeSystemConcept(code="5024", display="SMORFIA2"),
                CodeSystemConcept(code="5025", display="5 CO"),
                CodeSystemConcept(code="5026", display="6 CO"),
                CodeSystemConcept(code="5027", display="extra 2"),
                CodeSystemConcept(code="5028", display="4 CO"),
                CodeSystemConcept(code="5029", display="3 BA"),
                CodeSystemConcept(code="5030", display="extra 1"),
                CodeSystemConcept(code="5031", display="2 CO"),
                CodeSystemConcept(code="5032", display="Foto Simpatica 2"),
                CodeSystemConcept(code="5033", display="4 P inf / sfondo nero"),
                CodeSystemConcept(code="5034", display="9 MIP"),
                CodeSystemConcept(code="5035", display="6 P inf / sfondo nero"),
                CodeSystemConcept(code="5036", display="6 P sup / sfondo nero"),
                CodeSystemConcept(code="5037", display="1 RO sx"),
                CodeSystemConcept(code="5038", display="1 sx"),
                CodeSystemConcept(code="5039", display="1 S sx"),
                CodeSystemConcept(code="5040", display="PL DIGA 2"),
                CodeSystemConcept(code="5041", display="PL DIGA 3"),
                CodeSystemConcept(code="5042", display="3 P sx"),
                CodeSystemConcept(code="5043", display="3 P dx"),
                CodeSystemConcept(code="5044", display="3 P BA"),
                CodeSystemConcept(code="5045", display="Modelli frontali da sotto"),
                CodeSystemConcept(code="5046", display="3/4 dx RO "),
                CodeSystemConcept(code="5047", display="3/4 sx RO "),
                CodeSystemConcept(code="5048", display="extra 3"),
                CodeSystemConcept(code="5049", display="GEN 2"),
                CodeSystemConcept(code="5050", display="2 P BA"),
                CodeSystemConcept(code="5051", display="9 CO"),
                CodeSystemConcept(code="5052", display="5 P inf / sfondo nero"),
                CodeSystemConcept(code="5053", display="extra 4"),
                CodeSystemConcept(code="5054", display="BWdx"),
                CodeSystemConcept(code="5055", display="BWsx"),
                CodeSystemConcept(code="5056", display="DK"),
                CodeSystemConcept(code="5057", display="3/4 sx"),
                CodeSystemConcept(code="5058", display="3/4 dx"),
                CodeSystemConcept(code="5059", display="3/4 S dx"),
                CodeSystemConcept(code="5060", display="3/4 S sx"),
                CodeSystemConcept(code="5061", display="1 CO"),
                CodeSystemConcept(code="5062", display="GEN 7"),
                CodeSystemConcept(code="5063", display="GEN 3"),
                CodeSystemConcept(code="5064", display="2 P fonazione 1"),
                CodeSystemConcept(code="5065", display="2 P fonazione 2"),
                CodeSystemConcept(code="5066", display="2 P fonazione 3"),
                CodeSystemConcept(code="5067", display="4 P sup / sfondo nero"),
                CodeSystemConcept(code="5068", display="GEN 4"),
                CodeSystemConcept(code="5069", display="GEN 5"),
                CodeSystemConcept(code="5070", display="GEN 6"),
                CodeSystemConcept(code="5071", display="GEN 8"),
                CodeSystemConcept(code="5072", display="IP RP 5"),
                CodeSystemConcept(code="5073", display="IP RP 4"),
                CodeSystemConcept(code="5074", display="IP RP 6"),
                CodeSystemConcept(code="5075", display="RX6"),
                CodeSystemConcept(code="5076", display="RXE1"),
                CodeSystemConcept(code="5077", display="RXE2"),
                CodeSystemConcept(code="5078", display="RXE3"),
                CodeSystemConcept(code="5079", display="RXE4"),
                CodeSystemConcept(code="5080", display="RXE5"),
                CodeSystemConcept(code="5081", display="RXE6"),
                CodeSystemConcept(code="5082", display="RXE7"),
                CodeSystemConcept(code="5083", display="RXE8"),
                CodeSystemConcept(code="5084", display="RXE9"),
                CodeSystemConcept(code="5085", display="RXE10"),
                CodeSystemConcept(code="5086", display="RXE11"),
                CodeSystemConcept(code="5087", display="RXE12"),
                CodeSystemConcept(code="5088", display="RXE13"),
                CodeSystemConcept(code="5089", display="RXE14"),
                CodeSystemConcept(code="5090", display="RXE15"),
                CodeSystemConcept(code="5091", display="RXE16"),
                CodeSystemConcept(code="5092", display="RXE21"),
                CodeSystemConcept(code="5093", display="RXE17"),
                CodeSystemConcept(code="5094", display="RXE18"),
                CodeSystemConcept(code="5095", display="RXE19"),
                CodeSystemConcept(code="5096", display="RXE20"),
                CodeSystemConcept(code="5097", display="PL 2 P social smile"),
                CodeSystemConcept(code="5098", display="PL DIGA 4"),
                CodeSystemConcept(code="5099", display="STL 7"),
                CodeSystemConcept(code="5100", display="STL 8"),
                CodeSystemConcept(code="5101", display="STL 9"),
                CodeSystemConcept(code="5102", display="video 1"),
                CodeSystemConcept(code="5103", display="video 2"),
                CodeSystemConcept(code="5104", display="video 3"),
                CodeSystemConcept(code="5105", display="extra 5"),
                CodeSystemConcept(code="5106", display="extra 6"),
                CodeSystemConcept(code="5107", display="PL 1 P dx"),
                CodeSystemConcept(code="5108", display="PL 1 P RO dx"),
                CodeSystemConcept(code="5109", display="PL 1 S P social smile dx"),
                CodeSystemConcept(code="5110", display="PL 1 S P full smile dx"),
                CodeSystemConcept(code="5111", display="PL sorriso da sopra"),
                CodeSystemConcept(code="5112", display="PL 5 MIP  TQ dx"),
                CodeSystemConcept(code="5113", display="PL 5 MIP TQ sx"),
                CodeSystemConcept(code="5114", display="PL 5 P 2+2"),
                CodeSystemConcept(code="5115", display="RS sonda 1"),
                CodeSystemConcept(code="5116", display="RS sonda 2"),
                CodeSystemConcept(code="5117", display="RS sonda 3"),
                CodeSystemConcept(code="5118", display="RS sonda 4"),
                CodeSystemConcept(code="5119", display="RS sonda 5"),
                CodeSystemConcept(code="5120", display="RS sonda 6"),
                CodeSystemConcept(code="5121", display="RS sonda 7"),
                CodeSystemConcept(code="5122", display="RS sonda 8"),
                CodeSystemConcept(code="5123", display="RS sonda 9"),
                CodeSystemConcept(code="5124", display="RS sonda 10"),
                CodeSystemConcept(code="5125", display="RS sonda 11"),
                CodeSystemConcept(code="5126", display="RS sonda 12"),
                CodeSystemConcept(code="5127", display="RS sonda 13"),
                CodeSystemConcept(code="5128", display="RS sonda 14"),
                CodeSystemConcept(code="5129", display="RS sonda 15"),
                CodeSystemConcept(code="5130", display="RS sonda 16"),
                CodeSystemConcept(code="5131", display="RS sonda 17"),
                CodeSystemConcept(code="5132", display="RS sonda 18"),
                CodeSystemConcept(code="5133", display="1 P sx"),
                CodeSystemConcept(code="5134", display="1 P RO sx"),
                CodeSystemConcept(code="5135", display="1 P S sx"),
                CodeSystemConcept(code="5136", display="SDS 1"),
                CodeSystemConcept(code="5137", display="SDS 2"),
                CodeSystemConcept(code="5138", display="SDS 3"),
                CodeSystemConcept(code="5139", display="PL 2 P  full smile"),
            ]
        )